// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auditlog.sql

package dbtenant

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLogEntry = `-- name: CreateAuditLogEntry :one
INSERT INTO audit_log (
    user_id, api_key_id, action, resource, resource_id,
    detail, ip_address, user_agent
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, api_key_id, action, resource, resource_id, detail, ip_address, user_agent, created_at
`

type CreateAuditLogEntryParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	ApiKeyID   pgtype.UUID `json:"api_key_id"`
	Action     string      `json:"action"`
	Resource   string      `json:"resource"`
	ResourceID pgtype.UUID `json:"resource_id"`
	Detail     []byte      `json:"detail"`
	IpAddress  *netip.Addr `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLogEntry,
		arg.UserID,
		arg.ApiKeyID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Detail,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Detail,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, user_id, api_key_id, action, resource, resource_id, detail, ip_address, user_agent, created_at FROM audit_log
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Detail,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByResource = `-- name: ListAuditLogByResource :many
SELECT id, user_id, api_key_id, action, resource, resource_id, detail, ip_address, user_agent, created_at FROM audit_log
WHERE resource = $1 AND resource_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogByResourceParams struct {
	Resource   string      `json:"resource"`
	ResourceID pgtype.UUID `json:"resource_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListAuditLogByResource(ctx context.Context, arg ListAuditLogByResourceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByResource,
		arg.Resource,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Detail,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByUser = `-- name: ListAuditLogByUser :many
SELECT id, user_id, api_key_id, action, resource, resource_id, detail, ip_address, user_agent, created_at FROM audit_log
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAuditLogByUser(ctx context.Context, arg ListAuditLogByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Detail,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
