// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package dbtenant

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (space_id, parent_id, name, slug, icon, position, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, space_id, parent_id, name, slug, icon, position, created_by, created_at, updated_at
`

type CreateCollectionParams struct {
	SpaceID   uuid.UUID   `json:"space_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	Icon      pgtype.Text `json:"icon"`
	Position  int32       `json:"position"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.SpaceID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Position,
		arg.CreatedBy,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections
WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, space_id, parent_id, name, slug, icon, position, created_by, created_at, updated_at FROM collections
WHERE id = $1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id uuid.UUID) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollectionsBySpace = `-- name: ListCollectionsBySpace :many
SELECT id, space_id, parent_id, name, slug, icon, position, created_by, created_at, updated_at FROM collections
WHERE space_id = $1
ORDER BY position
`

func (q *Queries) ListCollectionsBySpace(ctx context.Context, spaceID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollectionsBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET name = $2, slug = $3, icon = $4, position = $5, parent_id = $6, updated_at = now()
WHERE id = $1
RETURNING id, space_id, parent_id, name, slug, icon, position, created_by, created_at, updated_at
`

type UpdateCollectionParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	Icon     pgtype.Text `json:"icon"`
	Position int32       `json:"position"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.Position,
		arg.ParentID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
