// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package dbtenant

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByDocument = `-- name: CountCommentsByDocument :one
SELECT COUNT(*) FROM comments
WHERE document_id = $1 AND is_deleted = false
`

func (q *Queries) CountCommentsByDocument(ctx context.Context, documentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByDocument, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (document_id, parent_id, author_id, body, body_rendered)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, document_id, parent_id, author_id, body, body_rendered, is_resolved, resolved_by, resolved_at, is_deleted, edited_at, created_at, updated_at
`

type CreateCommentParams struct {
	DocumentID   uuid.UUID   `json:"document_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	AuthorID     uuid.UUID   `json:"author_id"`
	Body         string      `json:"body"`
	BodyRendered string      `json:"body_rendered"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.DocumentID,
		arg.ParentID,
		arg.AuthorID,
		arg.Body,
		arg.BodyRendered,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.BodyRendered,
		&i.IsResolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.IsDeleted,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, document_id, parent_id, author_id, body, body_rendered, is_resolved, resolved_by, resolved_at, is_deleted, edited_at, created_at, updated_at FROM comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.BodyRendered,
		&i.IsResolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.IsDeleted,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsByDocument = `-- name: ListCommentsByDocument :many
SELECT id, document_id, parent_id, author_id, body, body_rendered, is_resolved, resolved_by, resolved_at, is_deleted, edited_at, created_at, updated_at FROM comments
WHERE document_id = $1 AND parent_id IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByDocument(ctx context.Context, documentID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ParentID,
			&i.AuthorID,
			&i.Body,
			&i.BodyRendered,
			&i.IsResolved,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.IsDeleted,
			&i.EditedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT id, document_id, parent_id, author_id, body, body_rendered, is_resolved, resolved_by, resolved_at, is_deleted, edited_at, created_at, updated_at FROM comments
WHERE parent_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListReplies(ctx context.Context, parentID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listReplies, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ParentID,
			&i.AuthorID,
			&i.Body,
			&i.BodyRendered,
			&i.IsResolved,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.IsDeleted,
			&i.EditedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveComment = `-- name: ResolveComment :exec
UPDATE comments
SET is_resolved = true, resolved_by = $2, resolved_at = now(), updated_at = now()
WHERE id = $1
`

type ResolveCommentParams struct {
	ID         uuid.UUID   `json:"id"`
	ResolvedBy pgtype.UUID `json:"resolved_by"`
}

func (q *Queries) ResolveComment(ctx context.Context, arg ResolveCommentParams) error {
	_, err := q.db.Exec(ctx, resolveComment, arg.ID, arg.ResolvedBy)
	return err
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments
SET body = '[deleted]', body_rendered = '[deleted]', is_deleted = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteComment, id)
	return err
}

const unresolveComment = `-- name: UnresolveComment :exec
UPDATE comments
SET is_resolved = false, resolved_by = NULL, resolved_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) UnresolveComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unresolveComment, id)
	return err
}

const updateCommentBody = `-- name: UpdateCommentBody :one
UPDATE comments
SET body = $2, body_rendered = $3, edited_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, document_id, parent_id, author_id, body, body_rendered, is_resolved, resolved_by, resolved_at, is_deleted, edited_at, created_at, updated_at
`

type UpdateCommentBodyParams struct {
	ID           uuid.UUID `json:"id"`
	Body         string    `json:"body"`
	BodyRendered string    `json:"body_rendered"`
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateCommentBody, arg.ID, arg.Body, arg.BodyRendered)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.BodyRendered,
		&i.IsResolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.IsDeleted,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
