// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package dbtenant

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDocuments = `-- name: CountDocuments :one
SELECT count(*) FROM documents
WHERE status != 'archived'
`

func (q *Queries) CountDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsBySpace = `-- name: CountDocumentsBySpace :one
SELECT count(*) FROM documents
WHERE space_id = $1 AND status != 'archived'
`

func (q *Queries) CountDocumentsBySpace(ctx context.Context, spaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsBySpace, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunbooks = `-- name: CountRunbooks :one
SELECT count(*) FROM documents
WHERE doc_type = 'runbook' AND status = 'published'
`

func (q *Queries) CountRunbooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRunbooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    space_id, collection_id, title, slug, content, content_text,
    doc_type, status, tags, icon, position, word_count,
    nightowl_incident_id, nightowl_alert_id, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, space_id, collection_id, title, slug, content, content_text, doc_type, status, tags, icon, position, word_count, version, nightowl_incident_id, nightowl_alert_id, search_vector, created_by, updated_by, created_at, updated_at
`

type CreateDocumentParams struct {
	SpaceID            uuid.UUID       `json:"space_id"`
	CollectionID       pgtype.UUID     `json:"collection_id"`
	Title              string          `json:"title"`
	Slug               string          `json:"slug"`
	Content            json.RawMessage `json:"content"`
	ContentText        string          `json:"content_text"`
	DocType            string          `json:"doc_type"`
	Status             string          `json:"status"`
	Tags               []string        `json:"tags"`
	Icon               pgtype.Text     `json:"icon"`
	Position           int32           `json:"position"`
	WordCount          int32           `json:"word_count"`
	NightowlIncidentID pgtype.Text     `json:"nightowl_incident_id"`
	NightowlAlertID    pgtype.Text     `json:"nightowl_alert_id"`
	CreatedBy          pgtype.UUID     `json:"created_by"`
	UpdatedBy          pgtype.UUID     `json:"updated_by"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.SpaceID,
		arg.CollectionID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.ContentText,
		arg.DocType,
		arg.Status,
		arg.Tags,
		arg.Icon,
		arg.Position,
		arg.WordCount,
		arg.NightowlIncidentID,
		arg.NightowlAlertID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.CollectionID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.ContentText,
		&i.DocType,
		&i.Status,
		&i.Tags,
		&i.Icon,
		&i.Position,
		&i.WordCount,
		&i.Version,
		&i.NightowlIncidentID,
		&i.NightowlAlertID,
		&i.SearchVector,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, space_id, collection_id, title, slug, content, content_text, doc_type, status, tags, icon, position, word_count, version, nightowl_incident_id, nightowl_alert_id, search_vector, created_by, updated_by, created_at, updated_at FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.CollectionID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.ContentText,
		&i.DocType,
		&i.Status,
		&i.Tags,
		&i.Icon,
		&i.Position,
		&i.WordCount,
		&i.Version,
		&i.NightowlIncidentID,
		&i.NightowlAlertID,
		&i.SearchVector,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentBySlug = `-- name: GetDocumentBySlug :one
SELECT id, space_id, collection_id, title, slug, content, content_text, doc_type, status, tags, icon, position, word_count, version, nightowl_incident_id, nightowl_alert_id, search_vector, created_by, updated_by, created_at, updated_at FROM documents
WHERE space_id = $1 AND slug = $2
`

type GetDocumentBySlugParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	Slug    string    `json:"slug"`
}

func (q *Queries) GetDocumentBySlug(ctx context.Context, arg GetDocumentBySlugParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentBySlug, arg.SpaceID, arg.Slug)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.CollectionID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.ContentText,
		&i.DocType,
		&i.Status,
		&i.Tags,
		&i.Icon,
		&i.Position,
		&i.WordCount,
		&i.Version,
		&i.NightowlIncidentID,
		&i.NightowlAlertID,
		&i.SearchVector,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunbookByID = `-- name: GetRunbookByID :one
SELECT id, title, slug, content, content_text, tags, updated_at
FROM documents
WHERE id = $1 AND doc_type = 'runbook'
`

type GetRunbookByIDRow struct {
	ID          uuid.UUID       `json:"id"`
	Title       string          `json:"title"`
	Slug        string          `json:"slug"`
	Content     json.RawMessage `json:"content"`
	ContentText string          `json:"content_text"`
	Tags        []string        `json:"tags"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) GetRunbookByID(ctx context.Context, id uuid.UUID) (GetRunbookByIDRow, error) {
	row := q.db.QueryRow(ctx, getRunbookByID, id)
	var i GetRunbookByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.ContentText,
		&i.Tags,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunbookWithSpace = `-- name: GetRunbookWithSpace :one
SELECT d.id, d.title, d.slug, d.content, d.content_text, d.tags, d.updated_at,
       s.slug AS space_slug
FROM documents d
JOIN spaces s ON s.id = d.space_id
WHERE d.id = $1 AND d.doc_type = 'runbook'
`

type GetRunbookWithSpaceRow struct {
	ID          uuid.UUID       `json:"id"`
	Title       string          `json:"title"`
	Slug        string          `json:"slug"`
	Content     json.RawMessage `json:"content"`
	ContentText string          `json:"content_text"`
	Tags        []string        `json:"tags"`
	UpdatedAt   time.Time       `json:"updated_at"`
	SpaceSlug   string          `json:"space_slug"`
}

func (q *Queries) GetRunbookWithSpace(ctx context.Context, id uuid.UUID) (GetRunbookWithSpaceRow, error) {
	row := q.db.QueryRow(ctx, getRunbookWithSpace, id)
	var i GetRunbookWithSpaceRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.ContentText,
		&i.Tags,
		&i.UpdatedAt,
		&i.SpaceSlug,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, space_id, collection_id, title, slug, content, content_text, doc_type, status, tags, icon, position, word_count, version, nightowl_incident_id, nightowl_alert_id, search_vector, created_by, updated_by, created_at, updated_at FROM documents
WHERE status != 'archived'
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.CollectionID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.ContentText,
			&i.DocType,
			&i.Status,
			&i.Tags,
			&i.Icon,
			&i.Position,
			&i.WordCount,
			&i.Version,
			&i.NightowlIncidentID,
			&i.NightowlAlertID,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByCollection = `-- name: ListDocumentsByCollection :many
SELECT id, space_id, collection_id, title, slug, content, content_text, doc_type, status, tags, icon, position, word_count, version, nightowl_incident_id, nightowl_alert_id, search_vector, created_by, updated_by, created_at, updated_at FROM documents
WHERE collection_id = $1 AND status != 'archived'
ORDER BY position
LIMIT $2 OFFSET $3
`

type ListDocumentsByCollectionParams struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) ListDocumentsByCollection(ctx context.Context, arg ListDocumentsByCollectionParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByCollection, arg.CollectionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.CollectionID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.ContentText,
			&i.DocType,
			&i.Status,
			&i.Tags,
			&i.Icon,
			&i.Position,
			&i.WordCount,
			&i.Version,
			&i.NightowlIncidentID,
			&i.NightowlAlertID,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsBySpace = `-- name: ListDocumentsBySpace :many
SELECT id, space_id, collection_id, title, slug, content, content_text, doc_type, status, tags, icon, position, word_count, version, nightowl_incident_id, nightowl_alert_id, search_vector, created_by, updated_by, created_at, updated_at FROM documents
WHERE space_id = $1 AND status != 'archived'
ORDER BY position, updated_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsBySpaceParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListDocumentsBySpace(ctx context.Context, arg ListDocumentsBySpaceParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsBySpace, arg.SpaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.CollectionID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.ContentText,
			&i.DocType,
			&i.Status,
			&i.Tags,
			&i.Icon,
			&i.Position,
			&i.WordCount,
			&i.Version,
			&i.NightowlIncidentID,
			&i.NightowlAlertID,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByType = `-- name: ListDocumentsByType :many
SELECT id, space_id, collection_id, title, slug, content, content_text, doc_type, status, tags, icon, position, word_count, version, nightowl_incident_id, nightowl_alert_id, search_vector, created_by, updated_by, created_at, updated_at FROM documents
WHERE doc_type = $1 AND status != 'archived'
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByTypeParams struct {
	DocType string `json:"doc_type"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListDocumentsByType(ctx context.Context, arg ListDocumentsByTypeParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByType, arg.DocType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.CollectionID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.ContentText,
			&i.DocType,
			&i.Status,
			&i.Tags,
			&i.Icon,
			&i.Position,
			&i.WordCount,
			&i.Version,
			&i.NightowlIncidentID,
			&i.NightowlAlertID,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunbooks = `-- name: ListRunbooks :many
SELECT id, title, slug, content_text, tags, updated_at
FROM documents
WHERE doc_type = 'runbook' AND status = 'published'
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListRunbooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRunbooksRow struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Slug        string    `json:"slug"`
	ContentText string    `json:"content_text"`
	Tags        []string  `json:"tags"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListRunbooks(ctx context.Context, arg ListRunbooksParams) ([]ListRunbooksRow, error) {
	rows, err := q.db.Query(ctx, listRunbooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunbooksRow{}
	for rows.Next() {
		var i ListRunbooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentText,
			&i.Tags,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunbooksWithSpace = `-- name: ListRunbooksWithSpace :many
SELECT d.id, d.title, d.slug, d.tags, d.updated_at,
       s.slug AS space_slug
FROM documents d
JOIN spaces s ON s.id = d.space_id
WHERE d.doc_type = 'runbook' AND d.status = 'published'
ORDER BY d.updated_at DESC
LIMIT $1 OFFSET $2
`

type ListRunbooksWithSpaceParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRunbooksWithSpaceRow struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Slug      string    `json:"slug"`
	Tags      []string  `json:"tags"`
	UpdatedAt time.Time `json:"updated_at"`
	SpaceSlug string    `json:"space_slug"`
}

func (q *Queries) ListRunbooksWithSpace(ctx context.Context, arg ListRunbooksWithSpaceParams) ([]ListRunbooksWithSpaceRow, error) {
	rows, err := q.db.Query(ctx, listRunbooksWithSpace, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunbooksWithSpaceRow{}
	for rows.Next() {
		var i ListRunbooksWithSpaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.UpdatedAt,
			&i.SpaceSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRunbooks = `-- name: SearchRunbooks :many
SELECT
    d.id, d.title, d.slug, d.tags, d.updated_at,
    s.slug AS space_slug,
    ts_rank(d.search_vector, plainto_tsquery('english', $1::text)) AS rank,
    ts_headline('english', d.content_text, plainto_tsquery('english', $1::text),
        'StartSel=<mark>, StopSel=</mark>, MaxWords=30, MinWords=15') AS excerpt
FROM documents d
JOIN spaces s ON s.id = d.space_id
WHERE d.doc_type = 'runbook'
  AND d.status = 'published'
  AND d.search_vector @@ plainto_tsquery('english', $1::text)
ORDER BY rank DESC
LIMIT $3 OFFSET $2
`

type SearchRunbooksParams struct {
	Query        string `json:"query"`
	ResultOffset int32  `json:"result_offset"`
	ResultLimit  int32  `json:"result_limit"`
}

type SearchRunbooksRow struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Slug      string    `json:"slug"`
	Tags      []string  `json:"tags"`
	UpdatedAt time.Time `json:"updated_at"`
	SpaceSlug string    `json:"space_slug"`
	Rank      float32   `json:"rank"`
	Excerpt   []byte    `json:"excerpt"`
}

func (q *Queries) SearchRunbooks(ctx context.Context, arg SearchRunbooksParams) ([]SearchRunbooksRow, error) {
	rows, err := q.db.Query(ctx, searchRunbooks, arg.Query, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRunbooksRow{}
	for rows.Next() {
		var i SearchRunbooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.UpdatedAt,
			&i.SpaceSlug,
			&i.Rank,
			&i.Excerpt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title = $2, slug = $3, content = $4, content_text = $5,
    collection_id = $6, doc_type = $7, status = $8, tags = $9, icon = $10,
    position = $11, word_count = $12, version = version + 1,
    nightowl_incident_id = $13, nightowl_alert_id = $14,
    updated_by = $15, updated_at = now()
WHERE id = $1
RETURNING id, space_id, collection_id, title, slug, content, content_text, doc_type, status, tags, icon, position, word_count, version, nightowl_incident_id, nightowl_alert_id, search_vector, created_by, updated_by, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID                 uuid.UUID       `json:"id"`
	Title              string          `json:"title"`
	Slug               string          `json:"slug"`
	Content            json.RawMessage `json:"content"`
	ContentText        string          `json:"content_text"`
	CollectionID       pgtype.UUID     `json:"collection_id"`
	DocType            string          `json:"doc_type"`
	Status             string          `json:"status"`
	Tags               []string        `json:"tags"`
	Icon               pgtype.Text     `json:"icon"`
	Position           int32           `json:"position"`
	WordCount          int32           `json:"word_count"`
	NightowlIncidentID pgtype.Text     `json:"nightowl_incident_id"`
	NightowlAlertID    pgtype.Text     `json:"nightowl_alert_id"`
	UpdatedBy          pgtype.UUID     `json:"updated_by"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.ContentText,
		arg.CollectionID,
		arg.DocType,
		arg.Status,
		arg.Tags,
		arg.Icon,
		arg.Position,
		arg.WordCount,
		arg.NightowlIncidentID,
		arg.NightowlAlertID,
		arg.UpdatedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.CollectionID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.ContentText,
		&i.DocType,
		&i.Status,
		&i.Tags,
		&i.Icon,
		&i.Position,
		&i.WordCount,
		&i.Version,
		&i.NightowlIncidentID,
		&i.NightowlAlertID,
		&i.SearchVector,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
