// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_images.sql

package dbtenant

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDocumentImagesByDocument = `-- name: DeleteDocumentImagesByDocument :exec
DELETE FROM document_images WHERE document_id = $1
`

func (q *Queries) DeleteDocumentImagesByDocument(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentImagesByDocument, documentID)
	return err
}

const deleteStaleDocumentImages = `-- name: DeleteStaleDocumentImages :exec
DELETE FROM document_images
WHERE document_id = $1
  AND storage_id != ALL($2::uuid[])
`

type DeleteStaleDocumentImagesParams struct {
	DocumentID uuid.UUID   `json:"document_id"`
	KeepIds    []uuid.UUID `json:"keep_ids"`
}

func (q *Queries) DeleteStaleDocumentImages(ctx context.Context, arg DeleteStaleDocumentImagesParams) error {
	_, err := q.db.Exec(ctx, deleteStaleDocumentImages, arg.DocumentID, arg.KeepIds)
	return err
}

const listDocumentImages = `-- name: ListDocumentImages :many
SELECT di.id, di.document_id, di.storage_id, di.created_at, so.storage_key
FROM document_images di
JOIN storage_objects so ON so.id = di.storage_id
WHERE di.document_id = $1
`

type ListDocumentImagesRow struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	StorageID  uuid.UUID `json:"storage_id"`
	CreatedAt  time.Time `json:"created_at"`
	StorageKey string    `json:"storage_key"`
}

func (q *Queries) ListDocumentImages(ctx context.Context, documentID uuid.UUID) ([]ListDocumentImagesRow, error) {
	rows, err := q.db.Query(ctx, listDocumentImages, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentImagesRow{}
	for rows.Next() {
		var i ListDocumentImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.StorageID,
			&i.CreatedAt,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocumentImage = `-- name: UpsertDocumentImage :exec
INSERT INTO document_images (document_id, storage_id)
VALUES ($1, $2)
ON CONFLICT (document_id, storage_id) DO NOTHING
`

type UpsertDocumentImageParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	StorageID  uuid.UUID `json:"storage_id"`
}

func (q *Queries) UpsertDocumentImage(ctx context.Context, arg UpsertDocumentImageParams) error {
	_, err := q.db.Exec(ctx, upsertDocumentImage, arg.DocumentID, arg.StorageID)
	return err
}
