// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documentversions.sql

package dbtenant

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (
    document_id, version, title, content, content_text,
    doc_type, tags, changed_by, change_summary
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, document_id, version, title, content, content_text, doc_type, tags, changed_by, change_summary, created_at
`

type CreateDocumentVersionParams struct {
	DocumentID    uuid.UUID       `json:"document_id"`
	Version       int32           `json:"version"`
	Title         string          `json:"title"`
	Content       json.RawMessage `json:"content"`
	ContentText   string          `json:"content_text"`
	DocType       string          `json:"doc_type"`
	Tags          []string        `json:"tags"`
	ChangedBy     pgtype.UUID     `json:"changed_by"`
	ChangeSummary pgtype.Text     `json:"change_summary"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.DocumentID,
		arg.Version,
		arg.Title,
		arg.Content,
		arg.ContentText,
		arg.DocType,
		arg.Tags,
		arg.ChangedBy,
		arg.ChangeSummary,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.ContentText,
		&i.DocType,
		&i.Tags,
		&i.ChangedBy,
		&i.ChangeSummary,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, document_id, version, title, content, content_text, doc_type, tags, changed_by, change_summary, created_at FROM document_versions
WHERE document_id = $1 AND version = $2
`

type GetDocumentVersionParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Version    int32     `json:"version"`
}

func (q *Queries) GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, arg.DocumentID, arg.Version)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.ContentText,
		&i.DocType,
		&i.Tags,
		&i.ChangedBy,
		&i.ChangeSummary,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentVersionByID = `-- name: GetDocumentVersionByID :one
SELECT id, document_id, version, title, content, content_text, doc_type, tags, changed_by, change_summary, created_at FROM document_versions
WHERE id = $1
`

func (q *Queries) GetDocumentVersionByID(ctx context.Context, id uuid.UUID) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersionByID, id)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.ContentText,
		&i.DocType,
		&i.Tags,
		&i.ChangedBy,
		&i.ChangeSummary,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, document_id, version, title, doc_type, tags, changed_by, change_summary, created_at
FROM document_versions
WHERE document_id = $1
ORDER BY version DESC
LIMIT $2 OFFSET $3
`

type ListDocumentVersionsParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListDocumentVersionsRow struct {
	ID            uuid.UUID   `json:"id"`
	DocumentID    uuid.UUID   `json:"document_id"`
	Version       int32       `json:"version"`
	Title         string      `json:"title"`
	DocType       string      `json:"doc_type"`
	Tags          []string    `json:"tags"`
	ChangedBy     pgtype.UUID `json:"changed_by"`
	ChangeSummary pgtype.Text `json:"change_summary"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]ListDocumentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, arg.DocumentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentVersionsRow{}
	for rows.Next() {
		var i ListDocumentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Version,
			&i.Title,
			&i.DocType,
			&i.Tags,
			&i.ChangedBy,
			&i.ChangeSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
