// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbtenant

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         uuid.UUID   `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	ApiKeyID   pgtype.UUID `json:"api_key_id"`
	Action     string      `json:"action"`
	Resource   string      `json:"resource"`
	ResourceID pgtype.UUID `json:"resource_id"`
	Detail     []byte      `json:"detail"`
	IpAddress  *netip.Addr `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Collection struct {
	ID        uuid.UUID   `json:"id"`
	SpaceID   uuid.UUID   `json:"space_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	Icon      pgtype.Text `json:"icon"`
	Position  int32       `json:"position"`
	CreatedBy pgtype.UUID `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Comment struct {
	ID           uuid.UUID          `json:"id"`
	DocumentID   uuid.UUID          `json:"document_id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	AuthorID     uuid.UUID          `json:"author_id"`
	Body         string             `json:"body"`
	BodyRendered string             `json:"body_rendered"`
	IsResolved   bool               `json:"is_resolved"`
	ResolvedBy   pgtype.UUID        `json:"resolved_by"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	IsDeleted    bool               `json:"is_deleted"`
	EditedAt     pgtype.Timestamptz `json:"edited_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type Document struct {
	ID                 uuid.UUID       `json:"id"`
	SpaceID            uuid.UUID       `json:"space_id"`
	CollectionID       pgtype.UUID     `json:"collection_id"`
	Title              string          `json:"title"`
	Slug               string          `json:"slug"`
	Content            json.RawMessage `json:"content"`
	ContentText        string          `json:"content_text"`
	DocType            string          `json:"doc_type"`
	Status             string          `json:"status"`
	Tags               []string        `json:"tags"`
	Icon               pgtype.Text     `json:"icon"`
	Position           int32           `json:"position"`
	WordCount          int32           `json:"word_count"`
	Version            int32           `json:"version"`
	NightowlIncidentID pgtype.Text     `json:"nightowl_incident_id"`
	NightowlAlertID    pgtype.Text     `json:"nightowl_alert_id"`
	SearchVector       interface{}     `json:"search_vector"`
	CreatedBy          pgtype.UUID     `json:"created_by"`
	UpdatedBy          pgtype.UUID     `json:"updated_by"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type DocumentImage struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	StorageID  uuid.UUID `json:"storage_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type DocumentVersion struct {
	ID            uuid.UUID       `json:"id"`
	DocumentID    uuid.UUID       `json:"document_id"`
	Version       int32           `json:"version"`
	Title         string          `json:"title"`
	Content       json.RawMessage `json:"content"`
	ContentText   string          `json:"content_text"`
	DocType       string          `json:"doc_type"`
	Tags          []string        `json:"tags"`
	ChangedBy     pgtype.UUID     `json:"changed_by"`
	ChangeSummary pgtype.Text     `json:"change_summary"`
	CreatedAt     time.Time       `json:"created_at"`
}

type DocumentYjsState struct {
	DocumentID uuid.UUID `json:"document_id"`
	YjsState   []byte    `json:"yjs_state"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Notification struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	Type       string      `json:"type"`
	DocumentID pgtype.UUID `json:"document_id"`
	CommentID  pgtype.UUID `json:"comment_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	IsRead     bool        `json:"is_read"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Space struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	IsPrivate   pgtype.Bool `json:"is_private"`
	CreatedBy   pgtype.UUID `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type SpaceMember struct {
	ID        uuid.UUID `json:"id"`
	SpaceID   uuid.UUID `json:"space_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type StorageObject struct {
	ID          uuid.UUID   `json:"id"`
	StorageKey  string      `json:"storage_key"`
	Filename    string      `json:"filename"`
	ContentType string      `json:"content_type"`
	SizeBytes   int64       `json:"size_bytes"`
	Backend     string      `json:"backend"`
	UploadedBy  pgtype.UUID `json:"uploaded_by"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Template struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	DocType     string          `json:"doc_type"`
	Content     json.RawMessage `json:"content"`
	Icon        pgtype.Text     `json:"icon"`
	IsSystem    bool            `json:"is_system"`
	IsGlobal    bool            `json:"is_global"`
	SpaceID     pgtype.UUID     `json:"space_id"`
	CreatedBy   pgtype.UUID     `json:"created_by"`
	SortOrder   int32           `json:"sort_order"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID   `json:"id"`
	ExternalID      string      `json:"external_id"`
	Email           string      `json:"email"`
	DisplayName     string      `json:"display_name"`
	Role            string      `json:"role"`
	IsActive        bool        `json:"is_active"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	Timezone        string      `json:"timezone"`
	AvatarStorageID pgtype.UUID `json:"avatar_storage_id"`
	AuthMethod      string      `json:"auth_method"`
}
