// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package dbtenant

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSpaceTree = `-- name: GetSpaceTree :many
SELECT
    c.id AS collection_id, c.name AS collection_name, c.slug AS collection_slug,
    c.parent_id, c.position AS collection_position, c.icon AS collection_icon,
    d.id AS document_id, d.title AS document_title, d.slug AS document_slug,
    d.doc_type, d.status, d.position AS document_position, d.icon AS document_icon
FROM collections c
LEFT JOIN documents d ON d.collection_id = c.id AND d.status != 'archived'
WHERE c.space_id = $1
ORDER BY c.position ASC, d.position ASC
`

type GetSpaceTreeRow struct {
	CollectionID       uuid.UUID   `json:"collection_id"`
	CollectionName     string      `json:"collection_name"`
	CollectionSlug     string      `json:"collection_slug"`
	ParentID           pgtype.UUID `json:"parent_id"`
	CollectionPosition int32       `json:"collection_position"`
	CollectionIcon     pgtype.Text `json:"collection_icon"`
	DocumentID         pgtype.UUID `json:"document_id"`
	DocumentTitle      pgtype.Text `json:"document_title"`
	DocumentSlug       pgtype.Text `json:"document_slug"`
	DocType            pgtype.Text `json:"doc_type"`
	Status             pgtype.Text `json:"status"`
	DocumentPosition   pgtype.Int4 `json:"document_position"`
	DocumentIcon       pgtype.Text `json:"document_icon"`
}

func (q *Queries) GetSpaceTree(ctx context.Context, spaceID uuid.UUID) ([]GetSpaceTreeRow, error) {
	rows, err := q.db.Query(ctx, getSpaceTree, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpaceTreeRow{}
	for rows.Next() {
		var i GetSpaceTreeRow
		if err := rows.Scan(
			&i.CollectionID,
			&i.CollectionName,
			&i.CollectionSlug,
			&i.ParentID,
			&i.CollectionPosition,
			&i.CollectionIcon,
			&i.DocumentID,
			&i.DocumentTitle,
			&i.DocumentSlug,
			&i.DocType,
			&i.Status,
			&i.DocumentPosition,
			&i.DocumentIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUncollectedDocuments = `-- name: GetUncollectedDocuments :many
SELECT id, title, slug, doc_type, status, position, icon
FROM documents
WHERE space_id = $1
  AND collection_id IS NULL
  AND status != 'archived'
ORDER BY position ASC, title ASC
`

type GetUncollectedDocumentsRow struct {
	ID       uuid.UUID   `json:"id"`
	Title    string      `json:"title"`
	Slug     string      `json:"slug"`
	DocType  string      `json:"doc_type"`
	Status   string      `json:"status"`
	Position int32       `json:"position"`
	Icon     pgtype.Text `json:"icon"`
}

func (q *Queries) GetUncollectedDocuments(ctx context.Context, spaceID uuid.UUID) ([]GetUncollectedDocumentsRow, error) {
	rows, err := q.db.Query(ctx, getUncollectedDocuments, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUncollectedDocumentsRow{}
	for rows.Next() {
		var i GetUncollectedDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.DocType,
			&i.Status,
			&i.Position,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocuments = `-- name: SearchDocuments :many
WITH fts AS (
    SELECT
        d.id, d.title, d.doc_type, d.slug, d.space_id, d.collection_id,
        s.name AS space_name, s.slug AS space_slug,
        ts_rank(d.search_vector, plainto_tsquery('english', $1::text)) AS rank,
        ts_headline('english', d.title, plainto_tsquery('english', $1::text)) AS title_highlight,
        ts_headline('english', d.content_text, plainto_tsquery('english', $1::text),
            'StartSel=<mark>, StopSel=</mark>, MaxWords=30, MinWords=15') AS content_highlight
    FROM documents d
    JOIN spaces s ON s.id = d.space_id
    WHERE d.search_vector @@ plainto_tsquery('english', $1::text)
      AND d.status != 'archived'
    ORDER BY rank DESC
    LIMIT $3 OFFSET $2
),
fuzzy AS (
    SELECT
        d.id, d.title, d.doc_type, d.slug, d.space_id, d.collection_id,
        s.name AS space_name, s.slug AS space_slug,
        GREATEST(
            similarity(d.title, $1::text),
            similarity(d.content_text, $1::text) * 0.5
        )::float4 AS rank,
        d.title AS title_highlight,
        '' AS content_highlight
    FROM documents d
    JOIN spaces s ON s.id = d.space_id
    WHERE d.status != 'archived'
      AND (d.title % $1::text OR d.content_text % $1::text)
      AND NOT EXISTS (SELECT 1 FROM fts WHERE fts.id = d.id)
    ORDER BY rank DESC
    LIMIT $3 OFFSET $2
)
SELECT id, title, doc_type, slug, space_id, collection_id, space_name, space_slug, rank, title_highlight, content_highlight FROM fts
UNION ALL
SELECT id, title, doc_type, slug, space_id, collection_id, space_name, space_slug, rank, title_highlight, content_highlight FROM fuzzy
`

type SearchDocumentsParams struct {
	Query        string `json:"query"`
	ResultOffset int32  `json:"result_offset"`
	ResultLimit  int32  `json:"result_limit"`
}

type SearchDocumentsRow struct {
	ID               uuid.UUID   `json:"id"`
	Title            string      `json:"title"`
	DocType          string      `json:"doc_type"`
	Slug             string      `json:"slug"`
	SpaceID          uuid.UUID   `json:"space_id"`
	CollectionID     pgtype.UUID `json:"collection_id"`
	SpaceName        string      `json:"space_name"`
	SpaceSlug        string      `json:"space_slug"`
	Rank             float32     `json:"rank"`
	TitleHighlight   []byte      `json:"title_highlight"`
	ContentHighlight []byte      `json:"content_highlight"`
}

func (q *Queries) SearchDocuments(ctx context.Context, arg SearchDocumentsParams) ([]SearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchDocuments, arg.Query, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsRow{}
	for rows.Next() {
		var i SearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DocType,
			&i.Slug,
			&i.SpaceID,
			&i.CollectionID,
			&i.SpaceName,
			&i.SpaceSlug,
			&i.Rank,
			&i.TitleHighlight,
			&i.ContentHighlight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentsBySpace = `-- name: SearchDocumentsBySpace :many
WITH fts AS (
    SELECT
        d.id, d.title, d.doc_type, d.slug, d.space_id, d.collection_id,
        s.name AS space_name, s.slug AS space_slug,
        ts_rank(d.search_vector, plainto_tsquery('english', $1::text)) AS rank,
        ts_headline('english', d.title, plainto_tsquery('english', $1::text)) AS title_highlight,
        ts_headline('english', d.content_text, plainto_tsquery('english', $1::text),
            'StartSel=<mark>, StopSel=</mark>, MaxWords=30, MinWords=15') AS content_highlight
    FROM documents d
    JOIN spaces s ON s.id = d.space_id
    WHERE d.search_vector @@ plainto_tsquery('english', $1::text)
      AND d.status != 'archived'
      AND d.space_id = $2
    ORDER BY rank DESC
    LIMIT $4 OFFSET $3
),
fuzzy AS (
    SELECT
        d.id, d.title, d.doc_type, d.slug, d.space_id, d.collection_id,
        s.name AS space_name, s.slug AS space_slug,
        GREATEST(
            similarity(d.title, $1::text),
            similarity(d.content_text, $1::text) * 0.5
        )::float4 AS rank,
        d.title AS title_highlight,
        '' AS content_highlight
    FROM documents d
    JOIN spaces s ON s.id = d.space_id
    WHERE d.status != 'archived'
      AND d.space_id = $2
      AND (d.title % $1::text OR d.content_text % $1::text)
      AND NOT EXISTS (SELECT 1 FROM fts WHERE fts.id = d.id)
    ORDER BY rank DESC
    LIMIT $4 OFFSET $3
)
SELECT id, title, doc_type, slug, space_id, collection_id, space_name, space_slug, rank, title_highlight, content_highlight FROM fts
UNION ALL
SELECT id, title, doc_type, slug, space_id, collection_id, space_name, space_slug, rank, title_highlight, content_highlight FROM fuzzy
`

type SearchDocumentsBySpaceParams struct {
	Query        string    `json:"query"`
	SpaceID      uuid.UUID `json:"space_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

type SearchDocumentsBySpaceRow struct {
	ID               uuid.UUID   `json:"id"`
	Title            string      `json:"title"`
	DocType          string      `json:"doc_type"`
	Slug             string      `json:"slug"`
	SpaceID          uuid.UUID   `json:"space_id"`
	CollectionID     pgtype.UUID `json:"collection_id"`
	SpaceName        string      `json:"space_name"`
	SpaceSlug        string      `json:"space_slug"`
	Rank             float32     `json:"rank"`
	TitleHighlight   []byte      `json:"title_highlight"`
	ContentHighlight []byte      `json:"content_highlight"`
}

func (q *Queries) SearchDocumentsBySpace(ctx context.Context, arg SearchDocumentsBySpaceParams) ([]SearchDocumentsBySpaceRow, error) {
	rows, err := q.db.Query(ctx, searchDocumentsBySpace,
		arg.Query,
		arg.SpaceID,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsBySpaceRow{}
	for rows.Next() {
		var i SearchDocumentsBySpaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DocType,
			&i.Slug,
			&i.SpaceID,
			&i.CollectionID,
			&i.SpaceName,
			&i.SpaceSlug,
			&i.Rank,
			&i.TitleHighlight,
			&i.ContentHighlight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentsByType = `-- name: SearchDocumentsByType :many
WITH fts AS (
    SELECT
        d.id, d.title, d.doc_type, d.slug, d.space_id, d.collection_id,
        s.name AS space_name, s.slug AS space_slug,
        ts_rank(d.search_vector, plainto_tsquery('english', $1::text)) AS rank,
        ts_headline('english', d.title, plainto_tsquery('english', $1::text)) AS title_highlight,
        ts_headline('english', d.content_text, plainto_tsquery('english', $1::text),
            'StartSel=<mark>, StopSel=</mark>, MaxWords=30, MinWords=15') AS content_highlight
    FROM documents d
    JOIN spaces s ON s.id = d.space_id
    WHERE d.search_vector @@ plainto_tsquery('english', $1::text)
      AND d.status != 'archived'
      AND d.doc_type = $2
    ORDER BY rank DESC
    LIMIT $4 OFFSET $3
),
fuzzy AS (
    SELECT
        d.id, d.title, d.doc_type, d.slug, d.space_id, d.collection_id,
        s.name AS space_name, s.slug AS space_slug,
        GREATEST(
            similarity(d.title, $1::text),
            similarity(d.content_text, $1::text) * 0.5
        )::float4 AS rank,
        d.title AS title_highlight,
        '' AS content_highlight
    FROM documents d
    JOIN spaces s ON s.id = d.space_id
    WHERE d.status != 'archived'
      AND d.doc_type = $2
      AND (d.title % $1::text OR d.content_text % $1::text)
      AND NOT EXISTS (SELECT 1 FROM fts WHERE fts.id = d.id)
    ORDER BY rank DESC
    LIMIT $4 OFFSET $3
)
SELECT id, title, doc_type, slug, space_id, collection_id, space_name, space_slug, rank, title_highlight, content_highlight FROM fts
UNION ALL
SELECT id, title, doc_type, slug, space_id, collection_id, space_name, space_slug, rank, title_highlight, content_highlight FROM fuzzy
`

type SearchDocumentsByTypeParams struct {
	Query        string `json:"query"`
	DocType      string `json:"doc_type"`
	ResultOffset int32  `json:"result_offset"`
	ResultLimit  int32  `json:"result_limit"`
}

type SearchDocumentsByTypeRow struct {
	ID               uuid.UUID   `json:"id"`
	Title            string      `json:"title"`
	DocType          string      `json:"doc_type"`
	Slug             string      `json:"slug"`
	SpaceID          uuid.UUID   `json:"space_id"`
	CollectionID     pgtype.UUID `json:"collection_id"`
	SpaceName        string      `json:"space_name"`
	SpaceSlug        string      `json:"space_slug"`
	Rank             float32     `json:"rank"`
	TitleHighlight   []byte      `json:"title_highlight"`
	ContentHighlight []byte      `json:"content_highlight"`
}

func (q *Queries) SearchDocumentsByType(ctx context.Context, arg SearchDocumentsByTypeParams) ([]SearchDocumentsByTypeRow, error) {
	rows, err := q.db.Query(ctx, searchDocumentsByType,
		arg.Query,
		arg.DocType,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentsByTypeRow{}
	for rows.Next() {
		var i SearchDocumentsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DocType,
			&i.Slug,
			&i.SpaceID,
			&i.CollectionID,
			&i.SpaceName,
			&i.SpaceSlug,
			&i.Rank,
			&i.TitleHighlight,
			&i.ContentHighlight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
