// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spaces.sql

package dbtenant

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (name, slug, description, icon, is_private, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, description, icon, is_private, created_by, created_at, updated_at
`

type CreateSpaceParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	IsPrivate   pgtype.Bool `json:"is_private"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
		arg.IsPrivate,
		arg.CreatedBy,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces
WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, name, slug, description, icon, is_private, created_by, created_at, updated_at FROM spaces
WHERE id = $1
`

func (q *Queries) GetSpaceByID(ctx context.Context, id uuid.UUID) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceByID, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpaceBySlug = `-- name: GetSpaceBySlug :one
SELECT id, name, slug, description, icon, is_private, created_by, created_at, updated_at FROM spaces
WHERE slug = $1
`

func (q *Queries) GetSpaceBySlug(ctx context.Context, slug string) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceBySlug, slug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, name, slug, description, icon, is_private, created_by, created_at, updated_at FROM spaces
ORDER BY name
`

func (q *Queries) ListSpaces(ctx context.Context) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Icon,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces
SET name = $2, slug = $3, description = $4, icon = $5, is_private = $6, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, description, icon, is_private, created_by, created_at, updated_at
`

type UpdateSpaceParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	IsPrivate   pgtype.Bool `json:"is_private"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
		arg.IsPrivate,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Icon,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
