// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spacemembers.sql

package dbtenant

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addSpaceMember = `-- name: AddSpaceMember :one
INSERT INTO space_members (space_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (space_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING id, space_id, user_id, role, created_at
`

type AddSpaceMemberParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
}

func (q *Queries) AddSpaceMember(ctx context.Context, arg AddSpaceMemberParams) (SpaceMember, error) {
	row := q.db.QueryRow(ctx, addSpaceMember, arg.SpaceID, arg.UserID, arg.Role)
	var i SpaceMember
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getSpaceMember = `-- name: GetSpaceMember :one
SELECT id, space_id, user_id, role, created_at FROM space_members
WHERE space_id = $1 AND user_id = $2
`

type GetSpaceMemberParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSpaceMember(ctx context.Context, arg GetSpaceMemberParams) (SpaceMember, error) {
	row := q.db.QueryRow(ctx, getSpaceMember, arg.SpaceID, arg.UserID)
	var i SpaceMember
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listSpaceMembers = `-- name: ListSpaceMembers :many
SELECT
    sm.id, sm.space_id, sm.user_id, sm.role, sm.created_at,
    u.email AS user_email,
    u.display_name AS user_display_name
FROM space_members sm
JOIN users u ON u.id = sm.user_id
WHERE sm.space_id = $1
ORDER BY u.display_name
`

type ListSpaceMembersRow struct {
	ID              uuid.UUID `json:"id"`
	SpaceID         uuid.UUID `json:"space_id"`
	UserID          uuid.UUID `json:"user_id"`
	Role            string    `json:"role"`
	CreatedAt       time.Time `json:"created_at"`
	UserEmail       string    `json:"user_email"`
	UserDisplayName string    `json:"user_display_name"`
}

func (q *Queries) ListSpaceMembers(ctx context.Context, spaceID uuid.UUID) ([]ListSpaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listSpaceMembers, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpaceMembersRow{}
	for rows.Next() {
		var i ListSpaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesForUser = `-- name: ListSpacesForUser :many
SELECT s.id, s.name, s.slug, s.description, s.icon, s.is_private, s.created_by, s.created_at, s.updated_at
FROM spaces s
JOIN space_members sm ON sm.space_id = s.id
WHERE sm.user_id = $1
ORDER BY s.name
`

func (q *Queries) ListSpacesForUser(ctx context.Context, userID uuid.UUID) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Icon,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSpaceMember = `-- name: RemoveSpaceMember :exec
DELETE FROM space_members
WHERE space_id = $1 AND user_id = $2
`

type RemoveSpaceMemberParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveSpaceMember(ctx context.Context, arg RemoveSpaceMemberParams) error {
	_, err := q.db.Exec(ctx, removeSpaceMember, arg.SpaceID, arg.UserID)
	return err
}
