// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage_objects.sql

package dbtenant

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStorageObject = `-- name: CreateStorageObject :one
INSERT INTO storage_objects (storage_key, filename, content_type, size_bytes, backend, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, storage_key, filename, content_type, size_bytes, backend, uploaded_by, created_at
`

type CreateStorageObjectParams struct {
	StorageKey  string      `json:"storage_key"`
	Filename    string      `json:"filename"`
	ContentType string      `json:"content_type"`
	SizeBytes   int64       `json:"size_bytes"`
	Backend     string      `json:"backend"`
	UploadedBy  pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateStorageObject(ctx context.Context, arg CreateStorageObjectParams) (StorageObject, error) {
	row := q.db.QueryRow(ctx, createStorageObject,
		arg.StorageKey,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Backend,
		arg.UploadedBy,
	)
	var i StorageObject
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Backend,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStorageObject = `-- name: DeleteStorageObject :exec
DELETE FROM storage_objects WHERE id = $1
`

func (q *Queries) DeleteStorageObject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStorageObject, id)
	return err
}

const getStorageObject = `-- name: GetStorageObject :one
SELECT id, storage_key, filename, content_type, size_bytes, backend, uploaded_by, created_at FROM storage_objects WHERE id = $1
`

func (q *Queries) GetStorageObject(ctx context.Context, id uuid.UUID) (StorageObject, error) {
	row := q.db.QueryRow(ctx, getStorageObject, id)
	var i StorageObject
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Backend,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageObjectByKey = `-- name: GetStorageObjectByKey :one
SELECT id, storage_key, filename, content_type, size_bytes, backend, uploaded_by, created_at FROM storage_objects WHERE storage_key = $1
`

func (q *Queries) GetStorageObjectByKey(ctx context.Context, storageKey string) (StorageObject, error) {
	row := q.db.QueryRow(ctx, getStorageObjectByKey, storageKey)
	var i StorageObject
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Backend,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listOrphanedStorageObjects = `-- name: ListOrphanedStorageObjects :many
SELECT so.id, so.storage_key
FROM storage_objects so
LEFT JOIN document_images di ON di.storage_id = so.id
WHERE di.id IS NULL
  AND so.created_at < now() - $1::interval
LIMIT 100
`

type ListOrphanedStorageObjectsRow struct {
	ID         uuid.UUID `json:"id"`
	StorageKey string    `json:"storage_key"`
}

func (q *Queries) ListOrphanedStorageObjects(ctx context.Context, minAge pgtype.Interval) ([]ListOrphanedStorageObjectsRow, error) {
	rows, err := q.db.Query(ctx, listOrphanedStorageObjects, minAge)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrphanedStorageObjectsRow{}
	for rows.Next() {
		var i ListOrphanedStorageObjectsRow
		if err := rows.Scan(&i.ID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
