// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package dbtenant

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, description, doc_type, content, icon, is_system, is_global, space_id, created_by, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, description, doc_type, content, icon, is_system, is_global, space_id, created_by, sort_order, created_at, updated_at
`

type CreateTemplateParams struct {
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	DocType     string          `json:"doc_type"`
	Content     json.RawMessage `json:"content"`
	Icon        pgtype.Text     `json:"icon"`
	IsSystem    bool            `json:"is_system"`
	IsGlobal    bool            `json:"is_global"`
	SpaceID     pgtype.UUID     `json:"space_id"`
	CreatedBy   pgtype.UUID     `json:"created_by"`
	SortOrder   int32           `json:"sort_order"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Name,
		arg.Description,
		arg.DocType,
		arg.Content,
		arg.Icon,
		arg.IsSystem,
		arg.IsGlobal,
		arg.SpaceID,
		arg.CreatedBy,
		arg.SortOrder,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocType,
		&i.Content,
		&i.Icon,
		&i.IsSystem,
		&i.IsGlobal,
		&i.SpaceID,
		&i.CreatedBy,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1 AND is_system = false
`

func (q *Queries) DeleteTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const getSystemTemplateByDocType = `-- name: GetSystemTemplateByDocType :one
SELECT id, name, description, doc_type, content, icon, is_system, is_global, space_id, created_by, sort_order, created_at, updated_at FROM templates
WHERE is_system = true AND doc_type = $1
ORDER BY sort_order
LIMIT 1
`

func (q *Queries) GetSystemTemplateByDocType(ctx context.Context, docType string) (Template, error) {
	row := q.db.QueryRow(ctx, getSystemTemplateByDocType, docType)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocType,
		&i.Content,
		&i.Icon,
		&i.IsSystem,
		&i.IsGlobal,
		&i.SpaceID,
		&i.CreatedBy,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemTemplateByName = `-- name: GetSystemTemplateByName :one
SELECT id, name, description, doc_type, content, icon, is_system, is_global, space_id, created_by, sort_order, created_at, updated_at FROM templates
WHERE is_system = true AND name = $1
LIMIT 1
`

func (q *Queries) GetSystemTemplateByName(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRow(ctx, getSystemTemplateByName, name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocType,
		&i.Content,
		&i.Icon,
		&i.IsSystem,
		&i.IsGlobal,
		&i.SpaceID,
		&i.CreatedBy,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, name, description, doc_type, content, icon, is_system, is_global, space_id, created_by, sort_order, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) GetTemplateByID(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocType,
		&i.Content,
		&i.Icon,
		&i.IsSystem,
		&i.IsGlobal,
		&i.SpaceID,
		&i.CreatedBy,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTemplates = `-- name: ListAllTemplates :many
SELECT id, name, description, doc_type, content, icon, is_system, is_global, space_id, created_by, sort_order, created_at, updated_at FROM templates
ORDER BY
    CASE WHEN is_system THEN 0 WHEN is_global THEN 1 ELSE 2 END,
    sort_order,
    name
`

func (q *Queries) ListAllTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listAllTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DocType,
			&i.Content,
			&i.Icon,
			&i.IsSystem,
			&i.IsGlobal,
			&i.SpaceID,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, description, doc_type, content, icon, is_system, is_global, space_id, created_by, sort_order, created_at, updated_at FROM templates
WHERE (is_system = true OR is_global = true OR space_id = $1::uuid)
ORDER BY
    CASE WHEN is_system THEN 0 WHEN is_global THEN 1 ELSE 2 END,
    sort_order,
    name
`

func (q *Queries) ListTemplates(ctx context.Context, spaceID uuid.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DocType,
			&i.Content,
			&i.Icon,
			&i.IsSystem,
			&i.IsGlobal,
			&i.SpaceID,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByDocType = `-- name: ListTemplatesByDocType :many
SELECT id, name, description, doc_type, content, icon, is_system, is_global, space_id, created_by, sort_order, created_at, updated_at FROM templates
WHERE doc_type = $1
  AND (is_system = true OR is_global = true OR space_id = $2::uuid)
ORDER BY
    CASE WHEN is_system THEN 0 WHEN is_global THEN 1 ELSE 2 END,
    sort_order,
    name
`

type ListTemplatesByDocTypeParams struct {
	DocType string    `json:"doc_type"`
	SpaceID uuid.UUID `json:"space_id"`
}

func (q *Queries) ListTemplatesByDocType(ctx context.Context, arg ListTemplatesByDocTypeParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByDocType, arg.DocType, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DocType,
			&i.Content,
			&i.Icon,
			&i.IsSystem,
			&i.IsGlobal,
			&i.SpaceID,
			&i.CreatedBy,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET name = $2, description = $3, content = $4, icon = $5, sort_order = $6, updated_at = now()
WHERE id = $1 AND is_system = false
RETURNING id, name, description, doc_type, content, icon, is_system, is_global, space_id, created_by, sort_order, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Content     json.RawMessage `json:"content"`
	Icon        pgtype.Text     `json:"icon"`
	SortOrder   int32           `json:"sort_order"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.Icon,
		arg.SortOrder,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocType,
		&i.Content,
		&i.Icon,
		&i.IsSystem,
		&i.IsGlobal,
		&i.SpaceID,
		&i.CreatedBy,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
