// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbtenant

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET is_active = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, email, display_name, role, is_active, created_at, updated_at, timezone, avatar_storage_id, auth_method FROM users
WHERE external_id = $1
`

func (q *Queries) GetUserByExternalID(ctx context.Context, externalID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.AvatarStorageID,
		&i.AuthMethod,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, external_id, email, display_name, role, is_active, created_at, updated_at, timezone, avatar_storage_id, auth_method FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.AvatarStorageID,
		&i.AuthMethod,
	)
	return i, err
}

const getUsersByEmails = `-- name: GetUsersByEmails :many
SELECT id, external_id, email, display_name, role, is_active, created_at, updated_at, timezone, avatar_storage_id, auth_method FROM users
WHERE email = ANY($1::text[]) AND is_active = true
`

func (q *Queries) GetUsersByEmails(ctx context.Context, emails []string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByEmails, emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Timezone,
			&i.AvatarStorageID,
			&i.AuthMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, external_id, email, display_name, role, is_active, created_at, updated_at, timezone, avatar_storage_id, auth_method FROM users
WHERE is_active = true
ORDER BY display_name
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Timezone,
			&i.AvatarStorageID,
			&i.AuthMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users
SET avatar_storage_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, external_id, email, display_name, role, is_active, created_at, updated_at, timezone, avatar_storage_id, auth_method
`

type UpdateUserAvatarParams struct {
	ID              uuid.UUID   `json:"id"`
	AvatarStorageID pgtype.UUID `json:"avatar_storage_id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.AvatarStorageID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.AvatarStorageID,
		&i.AuthMethod,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2, timezone = $3, updated_at = now()
WHERE id = $1
RETURNING id, external_id, email, display_name, role, is_active, created_at, updated_at, timezone, avatar_storage_id, auth_method
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Timezone    string    `json:"timezone"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.AvatarStorageID,
		&i.AuthMethod,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, updated_at = now()
WHERE id = $1
RETURNING id, external_id, email, display_name, role, is_active, created_at, updated_at, timezone, avatar_storage_id, auth_method
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.AvatarStorageID,
		&i.AuthMethod,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (external_id, email, display_name, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (external_id) DO UPDATE
SET email = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    updated_at = now()
RETURNING id, external_id, email, display_name, role, is_active, created_at, updated_at, timezone, avatar_storage_id, auth_method
`

type UpsertUserParams struct {
	ExternalID  string `json:"external_id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ExternalID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.AvatarStorageID,
		&i.AuthMethod,
	)
	return i, err
}
