apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bookowl.fullname" . }}
  labels:
    {{- include "bookowl.labels" . | nindent 4 }}
data:
  BOOKOWL_MODE: api
  BOOKOWL_PORT: {{ .Values.api.port | quote }}
  {{- if .Values.oidc.issuerUrl }}
  BOOKOWL_OIDC_ISSUER_URL: {{ .Values.oidc.issuerUrl | quote }}
  {{- end }}
  {{- if .Values.oidc.clientId }}
  BOOKOWL_OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  {{- end }}
  {{- if .Values.nightowl.apiUrl }}
  BOOKOWL_NIGHTOWL_API_URL: {{ .Values.nightowl.apiUrl | quote }}
  {{- end }}
