apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bookowl.fullname" . }}
  labels:
    {{- include "bookowl.labels" . | nindent 4 }}
data:
  APP_MODE: api
  APP_PORT: {{ .Values.api.port | quote }}
  {{- if .Values.oidc.issuerUrl }}
  OIDC_ISSUER: {{ .Values.oidc.issuerUrl | quote }}
  {{- end }}
  {{- if .Values.oidc.clientId }}
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  {{- end }}
  {{- if .Values.nightowl.apiUrl }}
  BOOKOWL_NIGHTOWL_API_URL: {{ .Values.nightowl.apiUrl | quote }}
  {{- end }}
  {{- if .Values.collab.wsUrl }}
  BOOKOWL_COLLAB_WS_URL: {{ .Values.collab.wsUrl | quote }}
  {{- end }}
