apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookowl.fullname" . }}-api
  labels:
    {{- include "bookowl.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "bookowl.apiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bookowl.apiSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bookowl.serviceAccountName" . }}
      containers:
        - name: api
          image: {{ include "bookowl.apiImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "bookowl.fullname" . }}
            {{- if or .Values.database.url .Values.redis.url .Values.nightowl.apiKey }}
            - secretRef:
                name: {{ include "bookowl.fullname" . }}
            {{- end }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
