{{- if or .Values.database.url .Values.redis.url .Values.nightowl.apiKey .Values.secretKey .Values.redis.password .Values.oidc.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookowl.fullname" . }}
  labels:
    {{- include "bookowl.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.database.url }}
  DATABASE_URL: {{ .Values.database.url | quote }}
  {{- end }}
  {{- if .Values.redis.url }}
  REDIS_URL: {{ .Values.redis.url | quote }}
  {{- end }}
  {{- if .Values.nightowl.apiKey }}
  BOOKOWL_NIGHTOWL_API_KEY: {{ .Values.nightowl.apiKey | quote }}
  {{- end }}
  {{- if .Values.secretKey }}
  BOOKOWL_SECRET_KEY: {{ .Values.secretKey | quote }}
  {{- end }}
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  {{- end }}
  {{- if .Values.oidc.clientSecret }}
  BOOKOWL_OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
  {{- if .Values.oidc.redirectUrl }}
  BOOKOWL_OIDC_REDIRECT_URL: {{ .Values.oidc.redirectUrl | quote }}
  {{- end }}
{{- end }}
