{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bookowl.fullname" . }}
  labels:
    {{- include "bookowl.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bookowl.apiSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
