{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bookowl.serviceAccountName" . }}
  labels:
    {{- include "bookowl.labels" . | nindent 4 }}
{{- end }}
