// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apikeys.sql

package dbglobal

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO public.api_keys (tenant_id, key_hash, key_prefix, description, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, key_hash, key_prefix, description, role, created_at
`

type CreateAPIKeyParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	KeyHash     string    `json:"key_hash"`
	KeyPrefix   string    `json:"key_prefix"`
	Description string    `json:"description"`
	Role        string    `json:"role"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.TenantID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Description,
		arg.Role,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Description,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM public.api_keys
WHERE id = $1 AND tenant_id = $2
`

type DeleteAPIKeyParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.TenantID)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT
    ak.id, ak.tenant_id, ak.key_hash, ak.key_prefix, ak.description, ak.role, ak.created_at,
    t.slug AS tenant_slug
FROM public.api_keys ak
JOIN public.tenants t ON t.id = ak.tenant_id
WHERE ak.key_hash = $1
`

type GetAPIKeyByHashRow struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	KeyHash     string    `json:"key_hash"`
	KeyPrefix   string    `json:"key_prefix"`
	Description string    `json:"description"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
	TenantSlug  string    `json:"tenant_slug"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Description,
		&i.Role,
		&i.CreatedAt,
		&i.TenantSlug,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, tenant_id, key_hash, key_prefix, description, role, created_at FROM public.api_keys
WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Description,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByTenant = `-- name: ListAPIKeysByTenant :many
SELECT id, tenant_id, key_hash, key_prefix, description, role, created_at FROM public.api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Description,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
