// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: local_admins.sql

package dbglobal

import (
	"context"

	"github.com/google/uuid"
)

const createLocalAdmin = `-- name: CreateLocalAdmin :one
INSERT INTO public.local_admins (tenant_slug, username, password_hash, must_change)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_slug, username, password_hash, must_change, last_login_at, created_at, updated_at
`

type CreateLocalAdminParams struct {
	TenantSlug   string `json:"tenant_slug"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	MustChange   bool   `json:"must_change"`
}

func (q *Queries) CreateLocalAdmin(ctx context.Context, arg CreateLocalAdminParams) (LocalAdmin, error) {
	row := q.db.QueryRow(ctx, createLocalAdmin,
		arg.TenantSlug,
		arg.Username,
		arg.PasswordHash,
		arg.MustChange,
	)
	var i LocalAdmin
	err := row.Scan(
		&i.ID,
		&i.TenantSlug,
		&i.Username,
		&i.PasswordHash,
		&i.MustChange,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalAdmin = `-- name: GetLocalAdmin :one
SELECT id, tenant_slug, username, password_hash, must_change, last_login_at, created_at, updated_at FROM public.local_admins
WHERE tenant_slug = $1 AND username = $2
`

type GetLocalAdminParams struct {
	TenantSlug string `json:"tenant_slug"`
	Username   string `json:"username"`
}

func (q *Queries) GetLocalAdmin(ctx context.Context, arg GetLocalAdminParams) (LocalAdmin, error) {
	row := q.db.QueryRow(ctx, getLocalAdmin, arg.TenantSlug, arg.Username)
	var i LocalAdmin
	err := row.Scan(
		&i.ID,
		&i.TenantSlug,
		&i.Username,
		&i.PasswordHash,
		&i.MustChange,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalAdminByTenant = `-- name: GetLocalAdminByTenant :one
SELECT id, tenant_slug, username, password_hash, must_change, last_login_at, created_at, updated_at FROM public.local_admins
WHERE tenant_slug = $1
`

func (q *Queries) GetLocalAdminByTenant(ctx context.Context, tenantSlug string) (LocalAdmin, error) {
	row := q.db.QueryRow(ctx, getLocalAdminByTenant, tenantSlug)
	var i LocalAdmin
	err := row.Scan(
		&i.ID,
		&i.TenantSlug,
		&i.Username,
		&i.PasswordHash,
		&i.MustChange,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLocalAdminLastLogin = `-- name: UpdateLocalAdminLastLogin :exec
UPDATE public.local_admins
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateLocalAdminLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLocalAdminLastLogin, id)
	return err
}

const updateLocalAdminPassword = `-- name: UpdateLocalAdminPassword :one
UPDATE public.local_admins
SET password_hash = $2, must_change = $3, updated_at = now()
WHERE id = $1
RETURNING id, tenant_slug, username, password_hash, must_change, last_login_at, created_at, updated_at
`

type UpdateLocalAdminPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
	MustChange   bool      `json:"must_change"`
}

func (q *Queries) UpdateLocalAdminPassword(ctx context.Context, arg UpdateLocalAdminPasswordParams) (LocalAdmin, error) {
	row := q.db.QueryRow(ctx, updateLocalAdminPassword, arg.ID, arg.PasswordHash, arg.MustChange)
	var i LocalAdmin
	err := row.Scan(
		&i.ID,
		&i.TenantSlug,
		&i.Username,
		&i.PasswordHash,
		&i.MustChange,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
