// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbglobal

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	KeyHash     string    `json:"key_hash"`
	KeyPrefix   string    `json:"key_prefix"`
	Description string    `json:"description"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID       `json:"id"`
	Slug      string          `json:"slug"`
	Name      string          `json:"name"`
	Config    json.RawMessage `json:"config"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}
