/* eslint-disable */
// @ts-nocheck

// This file is auto-generated by @tanstack/router-plugin.
// It will be regenerated when you run `npm run dev`.
// Do not edit this file manually.

export const routeTree = undefined as any
