/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces.$spaceId'
import { Route as ProfileTokensRouteImport } from './routes/profile.tokens'
import { Route as SpacesSpaceIdIndexRouteImport } from './routes/spaces.$spaceId.index'
import { Route as SpacesSpaceIdDocsDocIdRouteImport } from './routes/spaces.$spaceId.docs.$docId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTokensRoute = ProfileTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => ProfileRoute,
} as any)
const SpacesSpaceIdIndexRoute = SpacesSpaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)
const SpacesSpaceIdDocsDocIdRoute = SpacesSpaceIdDocsDocIdRouteImport.update({
  id: '/docs/$docId',
  path: '/docs/$docId',
  getParentRoute: () => SpacesSpaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/templates': typeof TemplatesRoute
  '/profile/tokens': typeof ProfileTokensRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/docs/$docId': typeof SpacesSpaceIdDocsDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/templates': typeof TemplatesRoute
  '/profile/tokens': typeof ProfileTokensRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/docs/$docId': typeof SpacesSpaceIdDocsDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/templates': typeof TemplatesRoute
  '/profile/tokens': typeof ProfileTokensRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRouteWithChildren
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/spaces/$spaceId/docs/$docId': typeof SpacesSpaceIdDocsDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/callback'
    | '/change-password'
    | '/login'
    | '/profile'
    | '/recent'
    | '/search'
    | '/templates'
    | '/profile/tokens'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/docs/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/callback'
    | '/change-password'
    | '/login'
    | '/profile'
    | '/recent'
    | '/search'
    | '/templates'
    | '/profile/tokens'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/docs/$docId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/callback'
    | '/change-password'
    | '/login'
    | '/profile'
    | '/recent'
    | '/search'
    | '/templates'
    | '/profile/tokens'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/docs/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CallbackRoute: typeof CallbackRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RecentRoute: typeof RecentRoute
  SearchRoute: typeof SearchRoute
  TemplatesRoute: typeof TemplatesRoute
  SpacesSpaceIdRoute: typeof SpacesSpaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId': {
      id: '/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/tokens': {
      id: '/profile/tokens'
      path: '/tokens'
      fullPath: '/profile/tokens'
      preLoaderRoute: typeof ProfileTokensRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/spaces/$spaceId/': {
      id: '/spaces/$spaceId/'
      path: '/'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof SpacesSpaceIdIndexRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
    '/spaces/$spaceId/docs/$docId': {
      id: '/spaces/$spaceId/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/spaces/$spaceId/docs/$docId'
      preLoaderRoute: typeof SpacesSpaceIdDocsDocIdRouteImport
      parentRoute: typeof SpacesSpaceIdRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileTokensRoute: typeof ProfileTokensRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileTokensRoute: ProfileTokensRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SpacesSpaceIdRouteChildren {
  SpacesSpaceIdIndexRoute: typeof SpacesSpaceIdIndexRoute
  SpacesSpaceIdDocsDocIdRoute: typeof SpacesSpaceIdDocsDocIdRoute
}

const SpacesSpaceIdRouteChildren: SpacesSpaceIdRouteChildren = {
  SpacesSpaceIdIndexRoute: SpacesSpaceIdIndexRoute,
  SpacesSpaceIdDocsDocIdRoute: SpacesSpaceIdDocsDocIdRoute,
}

const SpacesSpaceIdRouteWithChildren = SpacesSpaceIdRoute._addFileChildren(
  SpacesSpaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CallbackRoute: CallbackRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RecentRoute: RecentRoute,
  SearchRoute: SearchRoute,
  TemplatesRoute: TemplatesRoute,
  SpacesSpaceIdRoute: SpacesSpaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
